version: '2'
services:
  jenkins:
    build: .
    restart: always
    ports:
    - "7070:8080"
    volumes:
        - /opt/servers/jenkins:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker
    environment:
        - DOCKER_GID
